/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package From;

/**
 *
 * @author USER
 */
public class Calcular extends javax.swing.JFrame {

   

   /**
    * Creates new form Calcular
    */
   public Calcular() {
      initComponents();
      centrar();
   }
   public void centrar(){
      setLocationRelativeTo(null);
   }
   public void calcular(){
      int total = Integer.parseInt(txt_total.getText());
      int totalAyer = Integer.parseInt(txt_totalAyer.getText());
      int totalHoy = Integer.parseInt(txt_noHoy.getText());
      String Op = txt_opera.getText();
      String per = txt_person.getText();
      int Unahora = totalHoy/9;
      int PiFaltantes = (totalHoy + totalAyer) - total;
      int HorasFaltantes = PiFaltantes / Unahora;
      int DiasFaltantes = HorasFaltantes / 9;
   }
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      txt_totalAyer = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      txt_opera = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      txt_person = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txt_noHoy = new javax.swing.JTextField();
      txt_total = new javax.swing.JTextField();
      lb_1 = new javax.swing.JLabel();
      lb_2 = new javax.swing.JLabel();
      lb_3 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      txt_resumen = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("No. total de piezas realizadas :");

      jLabel2.setText("Operacion :");

      jLabel3.setText("Persona :");

      jLabel4.setText("No. piezas realizadas hoy :");

      jLabel5.setText("No. piezas Total del Corte :");

      lb_1.setBackground(new java.awt.Color(204, 204, 204));
      lb_1.setText("- - - - - - - - - - - - - - - - - ");

      lb_2.setText("- - - - - - - - - - - - - - - - - ");

      lb_3.setText("- - - - - - - - - - - - - - - - - ");

      jButton1.setBackground(new java.awt.Color(51, 204, 0));
      jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      jButton1.setForeground(new java.awt.Color(0, 0, 255));
      jButton1.setText("Calcular");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      txt_resumen.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
      txt_resumen.setText("                  - - - - - - - -                              - - - - - - -                        -- - - - - - -                              - - - - - - ");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(43, 43, 43)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel2)
               .addComponent(jLabel3)
               .addComponent(jLabel4)
               .addComponent(jLabel5)
               .addComponent(jLabel1))
            .addGap(37, 37, 37)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(txt_totalAyer)
               .addComponent(txt_opera)
               .addComponent(txt_person)
               .addComponent(txt_noHoy)
               .addComponent(txt_total, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(lb_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
               .addComponent(lb_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(lb_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(41, 41, 41))
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(txt_resumen, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(238, 238, 238)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(36, 36, 36)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel1)
                  .addComponent(txt_totalAyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(lb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(13, 13, 13)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2)
                     .addComponent(txt_opera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(txt_person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(lb_2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel4)
                  .addComponent(txt_noHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addComponent(lb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel5)
               .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(54, 54, 54)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(txt_resumen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(51, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int total = Integer.parseInt(txt_total.getText());
      int totalAyer = Integer.parseInt(txt_totalAyer.getText());
      int totalHoy = Integer.parseInt(txt_noHoy.getText());
      String Op = txt_opera.getText();
      String per = txt_person.getText();
      int Unahora = totalHoy/9;
//      double Unahora = Math.round(d*100.0)/100.0;
//      DecimalFormat df = new DecimalFormat("###.##");
      int PiFaltantes = total - (totalHoy + totalAyer);
      int HorasFaltantes = PiFaltantes / Unahora;
      int DiasFaltantes = HorasFaltantes / 9;
      
      lb_1.setText("En una hora realiza :" + Unahora);
      if (PiFaltantes < 1) {
         lb_2.setText(" Ya no faltan Piezas ");
         lb_3.setText("Ya no faltan Piezas ");
         txt_resumen.setText("SE TERMINO CON EXITO ");
      } else {
          lb_2.setText("Faltan " + PiFaltantes + " de piezas.");
          
         lb_3.setText("A este paso faltan " + HorasFaltantes + " horas.");
         txt_resumen.setText("La Operacion "+Op +" realizada por "+per+ " le faltan "+HorasFaltantes+" horas, o "+DiasFaltantes+" Dias.");
      }
      
   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new Calcular().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel lb_1;
   private javax.swing.JLabel lb_2;
   private javax.swing.JLabel lb_3;
   private javax.swing.JTextField txt_noHoy;
   private javax.swing.JTextField txt_opera;
   private javax.swing.JTextField txt_person;
   private javax.swing.JLabel txt_resumen;
   private javax.swing.JTextField txt_total;
   private javax.swing.JTextField txt_totalAyer;
   // End of variables declaration//GEN-END:variables
}
